### ISSUE TITLE
Tracker Error on Right Click

### ISSUE THREAD

**Issue by Marilith** [gameboy9/randoTracker#43]
Action:

Remotely connected tracker right clicks on tracker item.

Expected:

Displayed tracker item cycles backwards to the previous item in the list.

Result: 

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RandoTracker.Form1.changePicture(Int32 playerNumber, Int32 labelNumber, Boolean backwards)
   at RandoTracker.Form1.<>c__DisplayClass93_0.<OnRecievedDataServer>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by Datyedyeguy** [comment]
Appears to be the same error as #38.  Closing this as a dupe.
